### ISSUE TITLE
Chicago Accident Data

### ISSUE THREAD

**Issue by rajshah4** [UrbanCCD-UChicago/plenario#136]
Hi, how about incorporating the accident data for Chicago from 2009-2012?  I have another web site that shows the accident analysis (miningchi.com), but would love to have more tools for providing access to the data.  Its about 400,000 accidents and 200MB of data.  Let me know

**Comment by stevevance** [comment]
@vforgione Does that mean Plenario has the crash data?
I now have 2015 data.

**Comment by vforgione** [comment]
@stevevance: I'm not sure. I took lead of Plenario on Monday and I've been trying to categorize and close the backlog of issues. I figured since no one had responded to it for nearly 3 years that this wasn't a concern anymore. There were a bunch of open ended data requests from 2014 and early 2015 with no resolution and seemingly no interest to follow up.

I'm fine with reopening this and throwing it on the backlog. I'm working on a roadmap for the project right now, but to be honest backfilling data sets hasn't been communicated as a high priority. However, we will most likely upgrade the contribution API to make it easier for people to get more data in the system more easily.

**Comment by stevevance** [comment]
@vforgione I can prepare the Illinois crash data set into any format you want to make it easy to contribute it.

**Comment by lucaluca** [comment]
Back then we opened issues to track the things we needed to do before going alpha, but a few were lower priority at the time and got stranded. Some of them (like password reset) are probably still necessary if they haven't been resolved, but others like this data request are better tracked in another way.
