### ISSUE TITLE
Consider flattened /api/timeseries table

### ISSUE THREAD

**Issue by evz** [UrbanCCD-UChicago/plenario#145]
This is a view that gets hit quite a lot and the query can be quite slow. @derekeder and I were thinking about it this morning and it seems like one way of improving this is to just create a flattened version of what you get back from that query and store it in a separate table that gets updated when the data gets updated. 

This brings up a couple other things like how do we clean up when a dataset gets deleted but, that should be pretty straightforward if we're smart about it.

Relates to #112

**Comment by derekeder** [comment]
We're going to look into using a Postgres [materialized views](https://wiki.postgresql.org/wiki/Materialized_Views) for implementing this for the /timeseries api.

Relates to #141 and #176

**Comment by derekeder** [comment]
We're going to start working on a materialized view for this API endpoint and test the performance locally.

If that doesn't work, we'll look into creating a 3-dimensional index on the master table with timestamp, latitude and longitude and using either an [R-tree](https://en.wikipedia.org/wiki/R-tree) or [k-d tree](https://en.wikipedia.org/wiki/K-d_tree). This would take some significant re-engineering, but may be worth it in the long-term for the performance payoff.

**Comment by brettjgoldstein** [comment]
what is the update here?

**Comment by derekeder** [comment]
@brettjgoldstein see my previous comment. We're going to set up a [materialized view](https://wiki.postgresql.org/wiki/Materialized_Views) for the master table and see how that effects performance. Thoughts on that?

**Comment by brettjgoldstein** [comment]
I think that is a fine start.  When will it be live?  thx

Brett Goldstein
Senior Fellow in Urban Science
Harris School of Public Policy
University of Chicago
@bjgol



On June 25, 2015 at 3:42:03 PM, Derek Eder (notifications@github.com<mailto:notifications@github.com>) wrote:

@brettjgoldstein<https://github.com/brettjgoldstein> see my previous comment. We're going to set up a materialized view<https://wiki.postgresql.org/wiki/Materialized_Views> for the master table and see how that effects performance. Thoughts on that?

**Comment by derekeder** [comment]
We'll need to set it up and test locally, which we'll work on over the next week. If it works out, we can deploy it shortly after. If not, we'll have to think of another approach.

**Comment by HeyZoos** [comment]
Will has something that seems to work very well. You can emulate /timeseries by instead getting the dataset list and making several calls to /detail-aggregate. I've attached an ipython notebook to show performance comparisons.
[detail_aggregate vs timeseries.ipynb.zip](https://github.com/UrbanCCD-UChicago/plenario/files/286890/detail_aggregate.vs.timeseries.ipynb.zip)

**Comment by WillEngler** [comment]
^ To add some context to this, I may have stumbled on a quicker way to implement /timeseries by accident. For the frontend revamp, I wanted to lower latency from query submission on the main page to seeing the first timeseries result, so I launched a bunch of async calls to /detail-aggregate instead of one big one to /timeseries. This improves the user experience a lot, because you quickly get back most of the datasets covered by your query while the stragglers trickle in.

Unexpectedly, it seems to have improved throughput on the whole. So while /timeseries would often time out on a big enough space and time range, the async version got the last result in ~70 seconds max. That's anecdotal though, so Jesse is doing some benchmarking to see if it's really the case. And if it is, we can get the same throughput improvement on /timeseries by replicating the async calls on the backend (Instead of one monster call to Postgres, make one call for each dataset, then send the results out when the last one arrives. Poor man's map-reduce).

His first benchmark stacked the deck in favor of async because of how the order of the calls influenced DB-side cacheing, but he's setting up a fair fight now.

**Comment by WillEngler** [comment]
@HeyZoos gave it a second go over on the async-timeseries branch (fd11d57ad1f1c80c9fd60937e1b1613f33b70926). No significant difference between my proposed change and the old version. Thanks @HeyZoos for running the experiment. 

Frontend sluggishness was one of the big motivations to speed up `/timeseries`, but now that we've circumvented `/timeseries` and made the frontend zippier, we won't kill ourselves trying to make it super-fast.
