### ISSUE TITLE
ignore insane observation dates

### ISSUE THREAD

**Issue by derekeder** [UrbanCCD-UChicago/plenario#156]
Some of the datasets we have loaded in to Plenar.io have some observation dates that are hilariously far in the future - 7,000 years!

![screen shot 2014-11-26 at 10 42 34 am](https://cloud.githubusercontent.com/assets/919583/5204924/f46692fe-7558-11e4-9aa4-6ddbfb156b38.png)

This data should be fixed at the source (I've notified @levyj at the City of Chicago and @shua123 at Cook County), but in the meantime we can this them programmatically by ignoring `obs_to` dates anything more than, say, a year in to the future.

Handling this at the ETL stage makes the most sense to me: https://github.com/UrbanCCD-UChicago/plenario/blob/master/plenario/utils/etl.py#L697

**Comment by WillEngler** [comment]
The solution we took for this was twofold: 1) Rather than altering the data, we just added a filter on the frontend that doesn't show date ranges in that view if they're absurd. 2) Now that our ETL picks up changes in source datasets (as opposed to only adding brand-new records) we picked up fixes in source datasets that were causing this in the first place.
