### ISSUE TITLE
Datasets that fail to update are hidden from view

### ISSUE THREAD

**Issue by lucaluca** [UrbanCCD-UChicago/plenario#182]
Any dataset that fails to update properly gets removed from the "Explore" page even though it appears to still be accessible via API. We should keep the most recent version of the data in view even if the update fails, or we could break people's applications and generate confusion (e.g. I noticed @apanella re-submitted Chicago crimes because it appeared to be missing).

**Comment by WillEngler** [comment]
Fixed in e399acb. There is still a check for whether the last ETL job was successful in /api/timeseries/.  Still mulling over the implications of that.

**Comment by derekeder** [comment]
@WillEngler FYI removing [this line](https://github.com/UrbanCCD-UChicago/plenario/commit/e399acbe3c1f7beb325e3f4cd5e2fd19eaf59743#diff-216048aa0f7e9324db507f859749e3d4L143) will show all failing datasets on the front end. More details in #172

**Comment by WillEngler** [comment]
Thanks for the heads-up. Showing the failing datasets on the front end is what I intended to do. For example, the Chicago crimes dataset has been failing for a few weeks now, but I would still like it to be visible so that users can see all the years that we do have.

But what about complete duds like "San Francisco Pipeline Map First Quarter 2013" that never uploaded correctly at all? We definitely don't want to show that. For now, I'm planning on manually un-approving those to hide them from view.

Sound reasonable?

**Comment by derekeder** [comment]
@WillEngler definitely. having someone managing the ETL dashboard will be great for issues like this.
