### ISSUE TITLE
Use the hidden row id column in a Socrata dataset as the unique ID

### ISSUE THREAD

**Issue by levyj** [UrbanCCD-UChicago/plenario#187]
The Socrata SODA2 Resource API allows for including :id in the $select term, returning an internally maintained, unique ID for each row.  Apparently, it would take some modifications for Plenario to use it because Plenario uses the Socrata-provided metadata (from the Views API?) to determine the columns and :id is not included.  However, if those changes were made, every tabular Socrata dataset would meet the first requirement at http://plenar.io/contribute.

This idea should be vetted by Socrata (@chrismetcalf?) to make sure it is appropriate long term (or *now*) to depend on this feature.

@tomschenkjr @tsuchiyama

**Comment by chrismetcalf** [comment]
I think it's a solid idea, and I'd recommend you make use of the newest endpoint for each dataset to fetch the records with `:id`, so you can just use the `$select=:id,*` method to get the ID along with the rest of the data.

**Comment by lucaluca** [comment]
This could be a great solution to the problem. @chrismetcalf Does this unique ID stay with the row whenever new rows are added or the row is updated?

**Comment by tomschenkjr** [comment]
Question: if the ETL updates are only based on a unique ID, how will updates to a record (e.g., fixing data) get captured? Is it also relying on a “last updated” date as well?

**Comment by lucaluca** [comment]
Currently, the best solution is to hash the row and check the hashes against each other each time we update - if they don't match, we update. The unique ID is how we determine which hashes to check against each other. 

The issue with just using hashes as the unique IDs themselves is that if the row is updated, we don't have an easy way to tell *which* row was updated. But I think we'd love to hear any ideas or any processes DoIT has used in the past. It's okay if we have to create the unique ID ourselves, but is there a way that we could guarantee it stays the same even if the data is updated?

**Comment by levyj** [comment]
What we do is a combination of three things:


1)      Use a unique ID from the source system if it has one.

2)      Hash a set of columns that cannot change without it becoming a logically different record.  In effect, this means turning a composite primary key into a single-column primary key.  In some cases, I don’t think we even actually hash.  We simply concatenate.

3)      Nothing – no unique ID.  This is not uncommon and is the real barrier we are all trying to address here to keep it from making some datasets incompatible with Plenario.

By the way, we basically don’t do incremental updates for datasets, anymore.  We may still have some legacy ones but we don’t create new ones and have tried to update legacy ones to full replaces.  This is partly because Socrata implemented some nice technology that lets us send the complete file but it only changes the necessary dataset rows.  However, that really just enabled what I always wanted to do, anyway.  Any process with p > 0 of failing (i.e., every process) will fail eventually and our experience with ETLs has been that “eventually” is “reasonably often.”  That is also true of complete replaces but they are self-healing.  If the next run succeeds, you are good again.  With incremental updates, the outdated or missing data can linger until someone notices and fixes it.  No matter how clever we thought we were being in detecting all updates and deletions, things would fail eventually.

**Comment by WillEngler** [comment]
I like this idea. I do intend to change our ETL system such that we don't need a single ID column (I was thinking along the lines of @levyj's (2), some kind of composite key). But with the `:id` solution, we could get in a lot of Socrata data by changing the way we hit Socrata's API before I start on more time-consuming changes to the ETL.

I'm reluctant to plan in detail on how I'll implement the deeper ETL changes right now. That's largely because I don't have a good handle on our ETL module. A lot of the complexity (and, it seems, restrictions on incoming data) come from features that we were thinking of implementing once upon a time but decided to de-prioritize. Once I dig in and distinguish what's necessary and what's cruft, I'll be able to chime in with how I'd like to relax the unique ID restriction. In the mean time though, I'm devoting my development time to polygon work.

**Comment by WillEngler** [comment]
By the way, thanks to all for chiming in here. Great to get the perspective of people with so much experience in open data.

**Comment by chrismetcalf** [comment]
@lucaluca If the record is updated via upsert, and you use the internal identifier as the upsert identifier (i.e. you don't set your own identifier, and you include it with the record in your `POST`), the identifier will stay the same. If you use something like SmartUpdate via DataSync, it'll likely delete the row that has "disappeared" and create a new one with a new ID.

When building my own stuff with our API, I tend to go with either option #1 or #2 from the list @levyj provided above. Its easier to work with in most cases because unless you know the Socrata `:id` of the record you're trying to update, its easier to use an existing ID or generate a hash.

**Comment by WillEngler** [comment]
Update on the unique ID situation for @levyj and all else concerned.

I have a working re-implementation of our ETL that eliminates the need for a unique ID column at all (on the `hash-etl` branch). I'm working on migration right now and being very careful that this change won't disrupt anything during the OpenGrid launch week.

**Comment by WillEngler** [comment]
Resolved. See #188
