### ISSUE TITLE
No CSV option for /shapes/<polygon_dataset_name>/<point_dataset_name>/ 

### ISSUE THREAD

**Issue by lucaluca** [UrbanCCD-UChicago/plenario#219]
I'm trying to run [this query](http://plenar.io/v1/api/shapes/boundaries_zip_codes/crimes_2001_to_present/?obs_date__ge=2013-01-01&obs_date__le=2015-12-31&data_type=csv&iucr__in=0110,0130,0261,0262,0263,0264,0265,0266,0271,0272,0273,0274,0275,0281,0291,1753,1754,0312,0313,031A,031B,0320,0325,0326,0330,0331,0334,0337,033A,033B,0340,051A,051B,0520,0530,0550,0551,0552,0553,0555,0556,0557,0558,041A,041B,0420,0430,0450,0451,0452,0453,0461,0462,0479,0480,0481,0482,0483,0485,0488,0489,0490,0491,0492,0493,0495,0496,0497,0498,0510) and return a CSV, but the API seems to ignore the `data_type` parameter. 

Related point: perhaps these shape endpoints should return a meta.query object like the others, so we can see that the API interpreted the query properly.

**Comment by WillEngler** [comment]
1. Thanks for the bug report. As it happens, we haven't implemented CSV output for that endpoint, but we got carried away in copying over the documentation for the filters that it has in common with `/detail` and accidentally brought over `data_type`. Sorry about that. But we can get CSV support in this week. As the first external user of this feature, do you have any preference for what format the geometry comes in? I think [Well Known Text](http://www.skylinesoft.com/SkylineGlobe/TerraExplorer/v6.1.0/APIReferenceGuide/Well_Known_Text_and_Well_Known_Binary_WKT_and_WKB.htm) makes the most sense for CSV, but let me know if you think otherwise (if you're even using the geometry).
2. Agreed on your suggestion. The new spatial endpoints are still under construction, so some of the "polish" like meta.query isn't in yet. Expect them to be stable by end of April. (Where "stable" means that I won't make breaking changes until v2 of the API)

**Comment by lucaluca** [comment]
I'm using the endpoint to get counts of a dataset by geography, e.g. number of homicides by ZIP code. In that sense, something like a CSV would actually be easiest, though I don't need all the geometry information. In fact, I don't know if the geometry information would be valuable for others, either, since they can download that from the other endpoints, and this endpoint is really more about intersections. Might be able to save on response time and size by not including the geometry, just other information about the shape.

**Comment by WillEngler** [comment]
CSV support is up! I really appreciate you being an early user of this feature and giving us your feedback @lucaluca .

@ayang7 I used the `form_csv_detail_response` helper you made to hack this in quickly. But I took some shortcuts (especially around the way I'm grabbing the `data_type` parameter), so I'd still like for you to wrap up your implementation once finals madness dies down.
