### ISSUE TITLE
Plenar.io/explore not rendering

### ISSUE THREAD

**Issue by DruidSmith** [UrbanCCD-UChicago/plenario#273]
Plenar.io/explore page is not loading

Error: TypeError: Cannot read property 'map' of undefined

![image](https://cloud.githubusercontent.com/assets/187271/20765682/68286a14-b701-11e6-942f-465b0b5e6eed.png)

**Comment by WillEngler** [comment]
Thanks for pointing this out. The root cause of this was a transient network error affecting the backend. There was a gateway error preventing successful calls to our /shapes and /datasets endpoints. I was able to see the behavior you saw, but when I went to dig digger, it looks like the network issue was resolved.
